### ISSUE TITLE
Missing fake dependency

### ISSUE THREAD

**Issue by jitendravarma** [pratik141/nsedt#52]
After the lastest merge v0.0.12, its throwing

>>> from nsedt.reports import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/witchking/Code/scuti/nsedt/nsedt/reports.py", line 7, in <module>
    from nsedt.utils import get_cookies, fetch_csv, format_date, fetch_zip
  File "/Users/witchking/Code/scuti/nsedt/nsedt/utils/__init__.py", line 19, in <module>
    from fake_http_header import FakeHttpHeader
ModuleNotFoundError: No module named 'fake_http_header'

Although, I have added in requirements.txt and setup.py

**Comment by pratik141** [comment]
this will come in v0.0.13

**Comment by jitendravarma** [comment]
closing this present in 0.0.13
